---

- name: run sss_obfuscate so ldap_default_authtok is not plaintext
  shell: echo {{ sssd_domains[item]['ldap_default_authtok'] }} | sudo sss_obfuscate -d {{ item }} -f /etc/sssd/sssd.conf -s
  become: yes
  register: had_to_sss_obfuscate
  with_items: "{{ sssd_domains }}"
  when: sssd_domains[item].ldap_default_authtok is defined

# will restart only once, even if multiple obfuscations happen
- name: did obfuscation at least once, so restarting sssd service
  debug: msg="Had to obfuscate, so doing restart of sssd service"
  when: had_to_sss_obfuscate.changed
  notify:
    - restart sssd

